// Daily5 content pools. Each day the app deterministically picks one item
// from each pool (seeded by the date) so both friends see the same five cards.

const CONTENT = {
  trivia: [
    { q: "What is the only fruit with its seeds on the outside?", a: "The strawberry" },
    { q: "Which planet spins backwards compared to the others?", a: "Venus" },
    { q: "What animal's fingerprints are almost identical to a human's?", a: "The koala" },
    { q: "What is the national animal of Scotland?", a: "The unicorn" },
    { q: "How many hearts does an octopus have?", a: "Three" },
    { q: "What was the first toy advertised on television?", a: "Mr. Potato Head (1952)" },
    { q: "Which dessert is named after a Russian ballerina?", a: "The pavlova (after Anna Pavlova)" },
    { q: "What is a group of flamingos called?", a: "A flamboyance" },
    { q: "How long is a jiffy, scientifically speaking?", a: "1/100th of a second" },
    { q: "What color is a polar bear's skin under all that fur?", a: "Black" },
    { q: "Which food never spoils, even after thousands of years?", a: "Honey" },
    { q: "What percent of the human body is water?", a: "About 60%" },
    { q: "Which two U.S. states don't observe Daylight Saving Time?", a: "Hawaii and Arizona" },
    { q: "What was the first music video ever played on MTV?", a: "Video Killed the Radio Star by The Buggles" },
    { q: "How many bones does a shark have?", a: "Zero — sharks are all cartilage" },
    { q: "What was Google originally called?", a: "BackRub" },
    { q: "How many noses does a slug have?", a: "Four" },
    { q: "What's the only letter that doesn't appear in any U.S. state name?", a: "Q" },
    { q: "How many minutes does the average dream last?", a: "About 10–20 minutes" },
    { q: "What fruit was once known as a 'love apple'?", a: "The tomato" },
    { q: "Which country has the most islands in the world?", a: "Sweden (about 267,000)" },
    { q: "What's the strongest muscle in the human body relative to size?", a: "The masseter (jaw muscle)" },
    { q: "What do you call a group of pugs?", a: "A grumble" },
    { q: "What's the only mammal capable of true flight?", a: "The bat" },
    { q: "What's the most common birthday in the United States?", a: "September 9th" },
    { q: "How many times does the average person laugh per day?", a: "About 17 times" },
    { q: "What was the first item ever sold on eBay?", a: "A broken laser pointer" },
    { q: "Which animal can hold its breath the longest?", a: "The Cuvier's beaked whale (over 3 hours)" },
    { q: "What's the dot over the letters 'i' and 'j' called?", a: "A tittle" },
    { q: "How fast does a sneeze travel?", a: "Up to 100 mph" },
    { q: "What is banana-flavored candy actually based on?", a: "The Gros Michel banana, which mostly went extinct in the 1950s" },
    { q: "Which country drinks the most coffee per person?", a: "Finland" },
  ],

  qotd: [
    "What's a small thing that made you smile this week?",
    "If we could teleport to each other right now, what would we do first?",
    "What song have you had on repeat lately?",
    "What's something you're weirdly proud of?",
    "If you could master any skill overnight, what would it be?",
    "What's the best thing you ate this week?",
    "What's a memory of us that always makes you laugh?",
    "If you won the lottery tomorrow, what's the first ridiculous thing you'd buy?",
    "What's something you've changed your mind about recently?",
    "What's your current comfort show or movie?",
    "If your week was a movie genre, what genre would it be?",
    "What's one thing you're looking forward to this month?",
    "What would your 10-year-old self think of your life right now?",
    "What's a hot take you're willing to die on?",
    "If we opened a business together, what would it be?",
    "What's the last thing that gave you goosebumps?",
    "Who's a stranger you encountered recently that you still think about?",
    "What's your go-to order at your favorite spot right now?",
    "If you could relive one day of the past year, which would it be?",
    "What's something you want to try but haven't worked up the nerve for?",
    "What tiny luxury improves your life way more than it should?",
    "What's the weirdest dream you've had lately?",
    "If animals could talk, which species would be the rudest?",
    "What's your most-used emoji and does it define you?",
    "What's a compliment you received that you still think about?",
    "If today had a soundtrack, what's the opening track?",
    "What's one thing on your bucket list we should do together?",
    "What conspiracy theory do you lowkey think might be true?",
    "What's your ideal Sunday, hour by hour?",
    "What's something you miss about where you used to live?",
  ],

  challenge: [
    "Send a photo of you and your favorite bevy 🥤",
    "Send a photo of your view right now 🪟",
    "Send a selfie with your best 'Monday face' 😩",
    "Send a photo of the oldest thing in your fridge 🧀",
    "Send a picture of your shoes today 👟",
    "Send a photo of something coral-colored near you 🪸",
    "Send the last photo in your camera roll — no explanation allowed 📸",
    "Send a photo of your current snack situation 🍿",
    "Send a pic of the sky where you are ☁️",
    "Send a photo recreating your oldest selfie together 👯",
    "Send a voice memo singing the chorus of the last song you played 🎤",
    "Send a photo of your workspace, mess and all 🖥️",
    "Send a pic of something that reminded you of me this week 💭",
    "Send a photo of your dinner tonight, restaurant-review caption required 🍽️",
    "Send your best animal photo from your camera roll 🐾",
    "Send a photo of what you're wearing today, runway caption required 💅",
    "Send a screenshot of your most recent search history... if you dare 🔍",
    "Send a photo of your bedside table right now 🛏️",
    "Send a pic of your favorite mug or cup in action ☕",
    "Send a 5-second video of your best dance move 🕺",
    "Send a photo of the weirdest thing in your bag or pockets 🎒",
    "Send a screenshot of your lock screen 📱",
    "Send a photo doing your best impression of a renaissance painting 🎨",
    "Send a pic of tonight's sunset (or your lamp if you missed it) 🌅",
    "Send a photo of your plant, pet, or most alive-looking object 🌱",
  ],

  thisOrThat: [
    ["Beach vacation", "Mountain cabin"],
    ["Breakfast for dinner", "Dinner for breakfast"],
    ["Time travel to the past", "Time travel to the future"],
    ["Always slightly late", "Always 30 minutes early"],
    ["Iced coffee in winter", "Hot coffee in summer"],
    ["Karaoke night", "Trivia night"],
    ["Road trip", "Flight"],
    ["Sweet snacks", "Salty snacks"],
    ["Text person", "Call person"],
    ["Big party", "Small hangout"],
    ["Live in a city forever", "Live in a small town forever"],
    ["Rewatch old favorites", "Always something new"],
    ["Pancakes", "Waffles"],
    ["Night owl", "Early bird"],
    ["Invisible for a day", "Fly for a day"],
    ["Endless summer", "Endless fall"],
    ["Concert tickets", "Festival weekend"],
    ["Dogs", "Cats"],
    ["Cook together", "Order takeout together"],
    ["Board games", "Video games"],
    ["Museum date", "Hike date"],
    ["Never do laundry again", "Never do dishes again"],
    ["Front seat of the rollercoaster", "Solid ground, thanks"],
    ["Book the flight tonight", "Plan it for six months"],
    ["Bottomless brunch", "Late-night diner run"],
  ],

  wildcard: [
    "Rate your week 1–10 and give one word to explain the score 📊",
    "Describe your day using only emojis — I have to guess what happened 🧩",
    "Tell me one thing you never told me before 🤫",
    "Give me your top 3: songs, snacks, or shows this week 🏆",
    "Two truths and a lie — go! I'll guess the lie 🕵️",
    "What's our friendship's official theme song? Make your case 🎵",
    "Plan our next hangout in 3 emojis, I have to decode it 🗺️",
    "Send your most controversial food opinion 🌶️",
    "If I were a candle, what scent would I be? Be honest 🕯️",
    "Give me a weather report, but for your emotions ⛅",
    "Pitch me a movie where we're the main characters 🎬",
    "What's my most annoying habit? You get immunity today 😤",
    "Predict one thing that will happen to me this week 🔮",
    "Describe me in 5 words. Only 5. Choose wisely ✍️",
    "What would our friendship's warning label say? ⚠️",
    "Send the most unhinged photo of me you have 📸",
    "If we had a podcast, what's this week's episode title? 🎙️",
    "Write a one-star review of your own day 📝",
    "What's one thing I should absolutely do this weekend? Assign me homework 📚",
    "Speed round: last thing you cried about, laughed about, and googled 🏃",
  ],
};

// Trivia Battle question sets — 5 per day, drawn from the trivia pool by seed.
const GAMES = [
  {
    id: "ttt",
    name: "Tic-Tac-Toe",
    emoji: "⭕",
    players: 2,
    desc: "Classic 3-in-a-row. Make your move, send it, and wait for their comeback.",
  },
  {
    id: "emoji",
    name: "Emoji Riddle",
    emoji: "🧩",
    players: 2,
    desc: "Write a movie, song, or phrase in pure emoji. They guess, then tap to reveal.",
  },
  {
    id: "battle",
    name: "Trivia Battle",
    emoji: "⚔️",
    players: 2,
    desc: "Same 5 daily questions for both of you. Play, send your score, settle it.",
  },
];
